export const emoji = [
  { name: 'cat face with wry smile', symbol: '😼' },
  { name: 'grinning cat face with smiling eyes', symbol: '😸' },
  { name: 'grinning cat face', symbol: '😺' },
  { name: 'slightly smiling face', symbol: '🙂' },
  { name: 'smiling face with smiling eyes', symbol: '😊' },
  { name: 'winking face', symbol: '😉' },
  { name: 'grinning squinting face', symbol: '😆' },
  { name: 'grinning face with sweat', symbol: '😅' },
  { name: 'grinning face with smiling eyes', symbol: '😄' },
  { name: 'grinning face with big eyes', symbol: '😃' },
  { name: 'rolling on the floor laughing', symbol: '🤣' },
  { name: 'face with tears of joy', symbol: '😂' },
  { name: 'beaming face with smiling eyes', symbol: '😁' },
  { name: 'grinning face', symbol: '😀' },
  { name: 'pouting cat face', symbol: '😾' },
  { name: 'crying cat face', symbol: '😿' },
  { name: 'smiling cat face with heart-eyes', symbol: '😻' },
  { name: 'pouting face', symbol: '😡' },
  { name: 'anxious face with sweat', symbol: '😰' },
  { name: 'grimacing face', symbol: '😬' },
  { name: 'fearful face', symbol: '😨' },
  { name: 'anguished face', symbol: '😧' },
  { name: 'frowning face with open mouth', symbol: '😦' },
  { name: 'loudly crying face', symbol: '😭' },
  { name: 'face with steam from nose', symbol: '😤' },
  { name: 'squinting face with tongue', symbol: '😝' },
  { name: 'winking face with tongue', symbol: '😜' },
  { name: 'sad but relieved face', symbol: '😥' },
  { name: 'neutral face', symbol: '😐' },
  { name: 'face blowing a kiss', symbol: '😘' },
  { name: 'smiling face with heart-eyes', symbol: '😍' },
  { name: 'smiling face with sunglasses', symbol: '😎' },
  { name: 'face savoring food', symbol: '😋' },
  { name: 'melting face', symbol: '🫠' },
  { name: 'smiling face with halo', symbol: '😇' },
  { name: 'upside-down face', symbol: '🙃' },
  { name: 'grey heart', symbol: '🩶' },
  { name: 'light blue heart', symbol: '🩵' },
  { name: 'pink heart', symbol: '🩷' },
  { name: 'shaking face', symbol: '🫨' },
  { name: 'white heart', symbol: '🤍' },
  { name: 'brown heart', symbol: '🤎' },
  { name: 'mending heart', symbol: '❤️‍🩹' },
  { name: 'heart on fire', symbol: '❤️‍🔥' },
  { name: 'yawning face', symbol: '🥱' },
  { name: 'face holding back tears', symbol: '🥹' },
  { name: 'pleading face', symbol: '🥺' },
  { name: 'face with diagonal mouth', symbol: '🫤' },
  { name: 'disguised face', symbol: '🥸' },
  { name: 'partying face', symbol: '🥳' },
  { name: 'angry face with horns', symbol: '👿' },
  { name: 'angry face', symbol: '😠' },
  { name: 'pouting cat face', symbol: '😾' },
  { name: 'goblin', symbol: '👺' },
  { name: 'smiling face with horns', symbol: '😈' },
  { name: 'face with symbols on mouth', symbol: '🤬' },
  { name: 'pouting face', symbol: '😡' },
  { name: 'face with steam from nose', symbol: '😤' },
  { name: 'confounded face', symbol: '😖' },
  { name: 'persevering face', symbol: '😣' }
]
